epicures/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url 


from . import settings
from rating import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [   
    path('', include('rating.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rating/urls.py
from django.urls import path,include
from django.conf.urls import url 
from . import views

app_name = "rating"

urlpatterns = [
    path('index', views.index, name='index'),
    path('',views.homepage, name='homepage'), #a homepage function

    path('detail/<int:res_ID>/', views.detail, name='detail'), 
    path('delete/<int:res_ID>', views.destroy, name='delete'),
    path('edit/<int:res_ID>', views.edit, name='edit'),
    path('update/<int:res_ID>', views.update, name='update'), 
    path('insert', views.insert, name='insert'),
    path('res', views.res, name='res'), 
    path('search', views.search, name='search'), 
    path('recommend', views.recommend, name='recommend'),
    path('advanceSearch', views.advanceSearch, name='advanceSearch'), 
    path('ranking', views.ranking, name='ranking'), 
    path('person_rank', views.person_rank, name='person_rank'), 

]

user/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url 

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_request, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('information/', views.information, name="information"),
    path('profile/', views.profile, name="profile"),
    path('recommend_friend/', views.recommend_friend, name="recommend_friend"),
    path('visit/<int:res_ID>', views.visit, name="visit"),
    path('review/<int:dish_id>/<int:res_ID>', views.review, name="review"),
    path('edit_review/<int:review_id>', views.edit_review, name="edit_review"),
]

rating/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Restaurant(models.Model):
    res_ID = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200,null=True)
    score=models.FloatField(null=True,blank=True)
    number_of_visit = models.IntegerField(null=True)
    Cuisine_Type = models.CharField(max_length=255,null=True)
    Price_Range = models.IntegerField(null=True)
    Phone = models.CharField(max_length = 200,null=True)
    Address = models.CharField(max_length=255,null=True)
    Hours_Start = models.IntegerField(null=True)
    Hours_End = models.IntegerField(null=True)
    visit_by = models.ManyToManyField(User, symmetrical=True, blank=True)
    image = models.ImageField(upload_to='image',default ="/image/default.jpg",null=True)

    def __str__(self):
        return self.name


class Dish(models.Model):
    dish_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    price = models.FloatField(default=0,null=True)
    dish_type = models.CharField(max_length=200,null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    averageRating=models.FloatField(null=True)
    # class Meta:
    #     unique_together = (('restaurant', 'name'),)

    def __str__(self):
        return self.name

rating/forms.py
from django import forms  
from .models import Restaurant  
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self, commit=True): #.save means we want commit the data to save in SQL
        user = super(NewUserForm, self).save(commit=False) # not commit yet
        user.email = self.cleaned_data['email']
        if commit:
            user.save() # finally, we can commit
        return user
        
class RestaurantForm(forms.ModelForm):  
    class Meta:  
        model = Restaurant  
        fields = ('name', 'Address','Phone')

class CompleteForm(forms.ModelForm):  
    class Meta:  
        model = Restaurant  
        fields = ('name', 'Address','Phone','res_ID') #,'image')

rating/views.py
from django.shortcuts import render,get_object_or_404,redirect  
from .models import Restaurant,Dish
from user.models import Reviews,Information
from django.http import HttpResponse
from .forms import RestaurantForm,CompleteForm
from django.db import connection
from django.template import loader
from django.contrib import messages
import operator


def homepage(request):
    return render(request=request,template_name="home.html")

def index(request):
    res_list = Restaurant.objects.order_by('res_ID')[:]
    context = {'res_list': res_list}
    return render(request, 'index.html', context)

def detail(request, res_ID):
    current_user = request.user
    res_list = Restaurant.objects.get(pk=res_ID)
    with connection.cursor() as cursor:
        cursor.execute('''SELECT * FROM rating_restaurant_visit_by
                          WHERE user_id = %s AND restaurant_id = %s''',
                          [current_user.id, res_ID])
        visit = cursor.fetchall()
    flag = 0
    if visit: flag = 1 
    with connection.cursor() as cursor:
        cursor.execute('''SELECT d.name,r.rating,r.comment 
                          FROM user_reviews r JOIN rating_dish d
                          ON r.name_id=d.dish_id
                          WHERE r.rate_on_id = %s
                          LIMIT 8''',[res_ID])
        review = cursor.fetchall()

    with connection.cursor() as cursor:
        cursor.execute('''SELECT avg(rating) FROM user_reviews
                          WHERE rate_on_id = %s''',[res_ID])
        rate = cursor.fetchall()[0][0]
    menu = Dish.objects.filter(restaurant_id=res_ID)
    context = {'res_list': res_list, 'menu':menu, 'review':review, 'flag':flag, 'rate':rate}
    return render(request, 'detail.html', context)

def destroy(request, res_ID):  
    restaurant = Restaurant.objects.get(res_ID=res_ID)  
    restaurant.delete()  
    return redirect("/index") 

def edit(request, res_ID):  
    restaurant = Restaurant.objects.get(res_ID=res_ID)  
    return render(request,'edit.html', {'restaurant':restaurant})  

def update(request, res_ID):  
    restaurant = Restaurant.objects.get(pk=res_ID)
    form = RestaurantForm(request.POST, instance = restaurant)  
    if form.is_valid():  
        form.save()  
        return redirect("/index")   
    return redirect("/index") 

def insert(request):  
    return render(request,'insert.html') 

def res(request):   

    if request.method == "POST":  
        form = CompleteForm(request.POST)  
       
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/index')  
            except:  
                pass  
    else:  
        form = CompleteForm()  
    return render(request,'insert.html',{'form':form})  

def convert(stri):
    if not stri: stri = None
    return stri

def recommend(request):
    dish_type = convert(request.POST.get('dish_type'))

    with connection.cursor() as cursor:

        cursor.execute('''SELECT DISTINCT R1.res_ID
            FROM rating_Restaurant R1, rating_Dish M1
            WHERE M1.dish_type = %s AND R1.res_ID=M1.restaurant_id AND M1.restaurant_id IN
            (SELECT DISTINCT R.res_ID
            FROM rating_Dish M JOIN rating_Restaurant R
            ON R.res_ID=M.restaurant_id AND M.dish_type = %s
            GROUP BY R.res_ID)
            LIMIT 10''',[dish_type,dish_type])
        res = cursor.fetchall()

    res = [x[0] for x in res]
    res_list = Restaurant.objects.filter(res_ID__in=res)
    template = loader.get_template('result.html')
    context = {'res_list': res_list}
    return HttpResponse(template.render(context, request))

def search(request):
    r_name = convert(request.POST.get('name'))
    cuision_type = convert(request.POST.get('cuision_type'))
    address = convert(request.POST.get('address'))

    with connection.cursor() as cursor:
        cursor.execute('''SELECT r.res_ID FROM rating_Restaurant r
                          WHERE r.name = IFNULL(%s,r.name) AND r.Cuisine_Type = IFNULL(%s,r.Cuisine_Type) 
                          AND r.address = IFNULL(%s, r.address)''',
                       [r_name,cuision_type,address])
        res = cursor.fetchall()
 
    res = [x[0] for x in res]
    res_list = Restaurant.objects.filter(res_ID__in=res)
    template = loader.get_template('result.html')
    context = {'res_list': res_list}
    return HttpResponse(template.render(context, request))

def advanceSearch(request):
    return render(request=request, template_name="advanceSearch.html")


def get_ranking_parameter(W1,W2,W3,W4):
    print(W1,W2,W3,W4)
    avg_rating = dict()
    number_of_visit = dict()
    hours = dict()
    price = dict()
    name = dict()
    with connection.cursor() as cursor:
        cursor.execute('''SELECT number_of_visit, res_ID from rating_restaurant''')
        visit = cursor.fetchall()

    with connection.cursor() as cursor:
        cursor.execute('''SELECT Hours_End - Hours_Start, res_ID from rating_restaurant''')
        T = cursor.fetchall()

    with connection.cursor() as cursor:
        cursor.execute('''SELECT avg(rating),rate_on_id FROM user_reviews group by rate_on_id''')
        R = cursor.fetchall()

    with connection.cursor() as cursor:
        cursor.execute('''SELECT Price_Range, res_ID from rating_restaurant''')
        P = cursor.fetchall()
    
    with connection.cursor() as cursor:
        cursor.execute('''SELECT name, res_ID from rating_restaurant''')
        N = cursor.fetchall()

    for ele in visit:
        number_of_visit[ele[1]] = ele[0]

    for ele in R:
        avg_rating[ele[1]] = float(ele[0])

    for ele in T:
        hours[ele[1]] = ele[0]

    for ele in P:
        price[ele[1]] = ele[0]

    for ele in N:
        name[ele[1]] = ele[0]


    score = dict()

    Rmax = max(avg_rating.values())
    Rmin = min(avg_rating.values())
    Tmax = max(hours.values())
    Tmin = min(hours.values())
    Cmax = max(number_of_visit.values())
    Cmin = min(number_of_visit.values())
    Pmax = max(price.values())
    Pmin = min(price.values())

    for key in price:
        score[key] =  int(100*(W3*(avg_rating[key]-Rmin)/(Rmax-Rmin) + W1*(price[key]-Pmin)/(Pmax-Pmin) \
        + W2*(number_of_visit[key]-Cmin)/(Cmax-Cmin) + W4*(hours[key]-Tmin)/(Tmax - Tmin)))

    score = sorted(score.items(), key=operator.itemgetter(1),reverse=True)
    
    return score,name


def ranking(request):

    W1, W2, W3, W4 = 0.4, 0.2, 0.3, 0.1
    score, name = get_ranking_parameter(W1,W2,W3,W4)

    template = loader.get_template('rank_result.html')
    context = {'name': name, 'score':score}
    return HttpResponse(template.render(context, request))


def person_rank(request):
    if request.method == "POST":               
        W1 = float(request.POST.get('G1'))
        W2 = float(request.POST.get('G2'))
        W3 = float(request.POST.get('G3'))
        W4 = float(request.POST.get('G3'))
        sum_w = W1+W2+W3+W4

        score, name = get_ranking_parameter(W1/sum_w,W2/sum_w,W3/sum_w,W4/sum_w)

        template = loader.get_template('rank_result.html')
        context = {'name': name, 'score':score}
        return render(request,"person_rank.html",context)


    current_user = request.user
    information = Information.objects.get(user_id=current_user.id) 

    #number of visit in price in 3 level/total visit
    #number of visit in long hour/total visit
    #number of visit in high rating/total visit
    #number of visit in res with more visitors/total visit


    with connection.cursor() as cursor:
        cursor.execute('''SELECT avg(u.rating) FROM user_reviews u JOIN rating_restaurant r
            ON r.res_ID=u.rate_on_id where r.res_ID in 
            (SELECT DISTINCT rate_on_id FROM user_reviews 
            where rate_by_id = %s)''', [current_user.id])

        user_rating = cursor.fetchall()[0][0]

    with connection.cursor() as cursor:
        cursor.execute('''SELECT avg(Hours_End - Hours_Start), 
            avg(Price_Range),avg(number_of_visit)
            FROM rating_restaurant where res_ID in 
            (SELECT DISTINCT rate_on_id FROM user_reviews 
            where rate_by_id = %s)''', [current_user.id])

        user_average = cursor.fetchall()
    
    W1, W2, W3, W4 = 0.4, 0.2, 0.3, 0.1
    user_hour = user_average[0][0]
    user_visit = user_average[0][2]
    user_price = user_average[0][1]
    if user_rating and user_hour and user_visit and user_price:

        with connection.cursor() as cursor:
            cursor.execute('''SELECT avg(rating) FROM user_reviews''')
            rating = cursor.fetchall()[0][0]

        with connection.cursor() as cursor:
            cursor.execute('''SELECT avg(Hours_End - Hours_Start), 
                avg(Price_Range),avg(number_of_visit) FROM rating_restaurant''')
            overall = cursor.fetchall()

        c1 = float((user_price-overall[0][1])/overall[0][1])
        c2 = float((user_visit-overall[0][2])/overall[0][2])
        c3 = float((user_rating - rating)/rating)
        c4 = float((user_hour - overall[0][0])/overall[0][0])
        W1 = W1 +W1*c1
        W2 = W2 +W2*c2
        W3 = W3 +W3*c3
        W4 = W4 +W4*c4

    # W1 = information.Price
    # W2 = information.Visit
    # W3 = information.Rating
    # W4 = information.Duration

    sum_w = W1+W2+W3+W4

    score, name = get_ranking_parameter(W1/sum_w,W2/sum_w,W3/sum_w,W4/sum_w)

    context = {'name': name, 'score':score, 'W1':W1, 'W2':W2, 'W3':W3, 'W4':W4}

    return render(request,"person_rank.html",context)

rating/templates/advanceSearch.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}  

<style>
html{
  background:url(https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=karly-gomez-lK1Q5RyD6tc-unsplash.jpg) no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size:cover;
}
</style>

  <div class="row">
    <div class="col s12 m6 l8">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
			<h5>Search</h5>
			<form action="{% url 'rating:search'%}" method="POST">
			{% csrf_token %}
			<label>Name: </label><br>
			<input type="text" name="name"><br>
			<label>Cuision type: </label><br>
			<input type="text" name="cuision_type"><br>
			<label>Address: </label><br>
			<input type="text" name="address"><br>
			<input type="submit" value="submit">
			</form>
        </div>
      </div>
    </div>
  </div>


<div class="row">
    <div class="col s12 m6 l8">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
			<h5>Search By Dish Type</h5>
			<form action="{% url 'rating:recommend'%}" method="POST">
			{% csrf_token %}
			<label>Dish Type: </label><br>
			<input type="text" name="dish_type"><br>
			<input type="submit" value="submit">
			</form> 
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

rating/templates/detail.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
    <div class="content-section">
      <div class="restaurant">
        {% if user.is_authenticated %}
        {% if flag %}
            <div class="restaurant-rating">
                <center><a class="waves-effect grey btn">visited</a></center>
            </div>
        {% else %}
            <div class="visited">
                <center><a href="{% url 'user:visit' res_list.res_ID %}" class="btn btn-primary">visited</a></center>
            </div>
        {% endif %}
        {% endif %}
        <center><p>{{res_list.number_of_visit}} people has visited this restaurant.</p></center>
        <div class="restaurant-info">
          <h3 class="account-heading">{{res_list.name}}</h3>
          <p class="text-secondary"> Price Level(1-3):{{res_list.Price_Range}}</p>
          <p class="text-secondary"> Cuisine Type:{{res_list.Cuisine_Type}}
          </p>
          <p class="text-secondary"> Phone:{{res_list.Phone}}</p>
          <p class="text-secondary"> Address:{{res_list.Address}}</p>
          <p class="text-secondary"> Hours:{{res_list.Hours_Start}}:00 - {{res_list.Hours_End}}:00</p>

        </div>
      </div>
      
    </div>
    <h3 class="account-heading">Menu</h3>


    <html>
        <head>
            <style>
                table {
                    font-family: arial, sans-serif, font-size=1;
                    border-collapse: collapse;
                    width: 100%;
                }
            
            td, th {
                text-align: left;
                padding: 8px;
            }
            
            </style>
        </head>
        <body>
            
            <table>
                <tr>
                    <th>Dish Category</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Review</th>
                {% for r in menu %}
                </tr>
                <tr>
                    
                    <td>{{r.dish_type}}</td>
                    <td>{{r.name}}</td>
                    <td>{{r.price}}</td>
                    <td><a href="{% url 'user:review' dish_id=r.dish_id res_ID=res_list.res_ID %}"><span style="left: 2em;" class="glyphicon glyphicon-pencil">Write a Review</span></a> </td>
                    
                </tr>
                {% endfor %}
            </table>
            
        </body>
    </html>

    <h3 class="account-heading">Recent Review</h3>
    <p>Average Rating: {{rate}} </p>
    <html><head>
        <style>
            table {
                font-family: arial, sans-serif, font-size=1;
                border-collapse: collapse;
                width: 100%;
            }
        td, th {
            text-align: left;
            padding: 8px;
            width: 25% ;
        }
        </style>
        </head><body>
            
        <table>
            <tr>
                <th>Dish Name</th>
                <th>Rating</th>
                <th>Review</th>
            
            {% for r in review %}
            </tr>
            <tr>
                <td>{{r.0}}</td>
                <td>{{r.1}}</td>
                <td>{{r.2}}</td>
            </tr>
            {% endfor %}
        </table>
            
        </body>
    </html>
{% endblock content %}

rating/templates/edit.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
<form method="POST" class="post-form" action="{% url 'rating:update' restaurant.res_ID %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_ename" required maxlength="100" value="{{ restaurant.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Phone:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Phone" id="id_ephone" required maxlength="20" value="{{ restaurant.Phone }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Address:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Address" id="id_econtact" required maxlength="254" value="{{ restaurant.Address }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock content %}

rating/templates/header.html
<head>
{% load static %}
<link href="{% static 'tiny/css/prism.css' %}" rel="stylesheet">
<!-- Compiled and minified CSS -->

<link href="{% static 'rating/materialize.css' %}" rel="stylesheet">
<link href="{% static 'rating/style.css' %}" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>

    {% include "messages.html" %}

  <nav>
      <div class="nav-wrapper">
        <a href="{% url 'rating:homepage' %}" class="brand-logo"> &nbsp;  &nbsp; Epicures</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'rating:advanceSearch' %}">Advance Search</a></li>
          <li><a href="{% url 'rating:index' %}">Restaurants</a></li>

            {% if user.is_authenticated %}
              <li><a href="{% url 'user:information' %}">Information</a></li>
              <li><a href="{% url 'user:profile' %}">{{user.get_username}}</a></li>
              <li><a href="{% url 'user:logout' %}">Log Out</a></li>

            {% else %}
              <li><a href="{% url 'user:register' %}">Register</a></li>
              <li><a href="{% url 'user:login' %}">Log In</a></li>
            {% endif %}

<!--   <div class="search-container">
    <form action="/action_page.php">
      <input type="text" placeholder="Search.." name="search">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div> -->

        </ul>
      </div>
  </nav>

<p class="small">
 &nbsp;
</p>
<div class="container">
<!-- with the container, our register is not on the left anymore -->
{% block content %}
{% endblock %}
</div>
</body>

<script src="{% static 'tinymce/js/prism.js' %}"></script>

rating/templates/home.html
{% extends "header.html" %}<!-- extend some templates -->
{% load static %}



<td class="tdStyle"> 


  {% block content %}

<style>
html{
  background:url(https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=karly-gomez-lK1Q5RyD6tc-unsplash.jpg) no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size:cover;
}
</style>

  <div class="row">
    <div class="col s12 m6 l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <a href="{% url 'rating:person_rank'%}">Personalize Ranking</a>
        </div>
        <div class="card-action">
          <a href="{% url 'rating:ranking'%}">Get Ranking</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

rating/templates/index.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}

<style>
* {
  box-sizing: border-box;
}

.column {
  float: left;
  width: 33%;
  padding: 5px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}

</style>


{% if res_list %}
    <ul>
    <div class="row">
    {% for restaurant in res_list %}
    <div class="column">
        <td>  
            <li><a href="{% url 'rating:detail' restaurant.res_ID %}">{{ restaurant.name }}</a> 
                <br>
                <img src= {{restaurant.image.url}} width="250" height="250">
                <br>
                <div>
                    <a href="{% url 'rating:delete' restaurant.res_ID %}">Delete</a>
                    <a href="{% url 'rating:edit' restaurant.res_ID %}"><span style="margin-left: 2em;" class="glyphicon glyphicon-pencil">Edit</span></a> 
                </div>
            </li> 
        </td> 
      </div>
    {% endfor %}
    </div>
    </ul>
    <center><a href="{% url 'rating:insert' %}" class="btn btn-primary">Add New Record</a></center> 

{% else %}
    <p>No restaurant are available.</p>
{% endif %}

{% endblock content %}

rating/templates/insert.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
    
<form method="POST" class="post-form" action="{% url 'rating:res' %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h4>Enter Details</h4>  
    </div>  
  </div> 


   <div class="form-group row">  
     <label for="name">Restaurant Name:</label>
     <input type="text" id="id_name" name="name">
    </div> 

    <div class="form-group row">  
     <label for="name">Phone:</label>
     <input type="text" id="id_Phone" name="Phone">
    </div> 


    <div class="form-group row">  
     <label for="name">Address:</label>
     <input type="text" id="id_Address" name="Address">
    </div> 

    <div class="form-group row">  
     <label for="name">Restaurant ID:</label>
     <input type="number" id="id_ID" name="res_ID">
    </div> 

<!--     <div class="form-group row"> 
      <label for="name">Choose a profile picture:</label>
      <br>
      <input type="file" name="image" accept="image/*">
    </div>  -->
 
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div> 


  </div>  
    </div>  
</form> 
{% endblock content %}

rating/templates/messages.html
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}

rating/templates/person_rank.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
{% load rating_extras %}

{% if user.is_authenticated %}
<!-- <div style="width:300px; height:auto; float:left; display:inline">AAAA</div> 
<div style="width:300px; height:auto; float:left; display:inline">BBBB</div> -->

  <div style="float: left;">

	<h5>Ranking based on your profile and preference</h5>
	    <ul>
	    {% for key, val in score %}
		    
	        <li>score: {{val}} &nbsp;  &nbsp;  &nbsp; <a href="{% url 'rating:detail' key %}">{{name|keyvalue:key}}</a> 

	    {% endfor %}
	    </ul> 
  </div>

  <div style="float: right;">

	<h6>Enter perfered weight for ranking</h6>
	<form action="{% url 'rating:person_rank'%}" method="POST">
	{% csrf_token %}
	<label>Rating(0 to 1): </label><br>
	<input type="number" step="any" name="G3" value="{{ W3 }}"><br>
	<label>Duration of Openning(0 to 1): </label><br>
	<input type="number" step="any" name="G4" value="{{ W4 }}"><br>
	<label>Total Visit(0 to 1): </label><br>
	<input type="number" step="any" name="G2" value="{{ W2 }}"><br>
	<label>Price Level(0 to 1): </label><br>
	<input type="number" step="any" name="G1" value="{{ W1 }}"><br>

	<input type="submit" value="submit">
	</form>  
  </div>

{% else %}
    <h5>Please Login to See result</h5>

{% endif %}

{% endblock content %}

rating/templates/rank_result.html
{% extends "header.html" %}<!-- extend some templates -->
{% load rating_extras %}

{% block content %}
	<h5>Ranking Result</h5>
    <ul>
    {% for key, val in score %}
	    
        <li>score: {{val}} &nbsp;  &nbsp;  &nbsp; <a href="{% url 'rating:detail' key %}">{{name|keyvalue:key}}</a> 


    {% endfor %}
    </ul>

{% endblock %}

rating/templates/result.html
{% extends "header.html" %}<!-- extend some templates -->


{% block content %}

<style>
* {
  box-sizing: border-box;
}

.column {
  float: left;
  width: 33%;
  padding: 5px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}

</style>


{% if res_list %}
    <ul>
    <div class="row">
    {% for restaurant in res_list %}
    <div class="column">
        <td>  
            <li><a href="{% url 'rating:detail' restaurant.res_ID %}">{{ restaurant.name }}</a> 
                <br>
                <img src= {{restaurant.image.url}} width="250" height="250">
                <br>
            </li> 
        </td> 
      </div>
    {% endfor %}
    </div>
    </ul>

{% else %}
    <p>No restaurant are available.</p>
{% endif %}

{% endblock %}