epicures/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url 


from . import settings
from rating import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [   
    path('', include('rating.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url 

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_request, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('information/', views.information, name="information"),
    path('profile/', views.profile, name="profile"),
    path('recommend_friend/', views.recommend_friend, name="recommend_friend"),
    path('visit/<int:res_ID>', views.visit, name="visit"),
    path('review/<int:dish_id>/<int:res_ID>', views.review, name="review"),
    path('edit_review/<int:review_id>', views.edit_review, name="edit_review"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from rating.models import Restaurant, Dish

# Create your models here.

class Information(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    FirstName = models.CharField(max_length=200,null=True)
    Major = models.CharField(max_length=200,null=True)
    Gender = models.CharField(max_length=200,null=True)
    Favorite_Cuision = models.CharField(max_length=200,null=True)
    Favorite_Restaurant = models.CharField(max_length=200,null=True)
    Rating = models.IntegerField(default=1,null=True)
    Duration = models.IntegerField(default=1,null=True)
    Visit = models.IntegerField(default=1,null=True)
    Price = models.IntegerField(default=1,null=True)

    def __str__(self):
        return self.user.username

class Friendship(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False,null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friendship_creator")
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend")

    def __str__(self):
        return self.creator

class Reviews(models.Model):
    comment = models.CharField(max_length=250)
    rating = models.IntegerField(default=0,null=True)
    name = models.ForeignKey(Dish, on_delete=models.CASCADE)
    rate_on = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    rate_by = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Information,Reviews

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self, commit=True): #.save means we want commit the data to save in SQL
        user = super(NewUserForm, self).save(commit=False) # not commit yet
        user.email = self.cleaned_data['email']
        if commit:
            user.save() # finally, we can commit
        return user

class InformationForm(forms.ModelForm):

    class Meta:
        model = Information 
        fields = ['FirstName','Major','Gender','Favorite_Cuision','Favorite_Restaurant']

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Reviews 
        fields = ['rating','comment']

user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.db import connection
from .forms import NewUserForm,InformationForm, ReviewForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from .models import Friendship,Information,Reviews


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/")
        else:
            messages.error(request, "Invalid username or password")
                
    form = UserCreationForm
    return render(request,"register.html", {"form":form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                messages.info(request, "You are now logged in as username")
                return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request, "login.html", {"form":form})


@login_required
def information(request):
    current_user = request.user
    information = Information.objects.get(user_id=current_user.id)  

    if request.method == 'POST':
        form = InformationForm(request.POST,request.FILES,instance=request.user.information)
        form.save()
        if form.is_valid():
            form.save()
            messages.success(request,'successfuly Updated!')
            return redirect("/profile")
    else:
        form = InformationForm(instance=request.user.information)
        # form = InformationForm()
    context = {'form':form, 'information':information}
    return render(request,'information.html',context)

@login_required
def review(request,dish_id,res_ID):
    if request.method == 'POST':
        current_user = request.user
        comment = request.POST.get('comment')
        rating = request.POST.get('rating')

        with connection.cursor() as cursor:
            cursor.execute('''INSERT INTO user_reviews(comment,rating,name_id, rate_by_id, rate_on_id) 
                              VALUES(%s, %s, %s, %s, %s)''',
                              [comment,rating,dish_id,current_user.id,res_ID])

        url = "/detail/" + str(res_ID)
        return redirect(url) 

    context = {'dish_id': dish_id, 'res_ID':res_ID}
    return render(request, 'review.html', context)

@login_required
def visit(request, res_ID):  
    current_user = request.user
    with connection.cursor() as cursor:
        cursor.execute('''INSERT INTO rating_restaurant_visit_by(restaurant_id, user_id) VALUES(%s, %s);''',
                       [res_ID,current_user.id])

        cursor.execute('''UPDATE rating_restaurant SET number_of_visit = 1+ number_of_visit WHERE res_ID = %s;''',[res_ID])
    url = "/detail/" + str(res_ID)
    return redirect(url) 

@login_required
def profile(request):
    current_user = request.user
    profile = Information.objects.get(user_id=current_user.id)
    with connection.cursor() as cursor:
        cursor.execute('''SELECT res.name, d.name,r.rating,r.comment,r.id
                          FROM (user_reviews r JOIN rating_dish d
                          ON r.name_id=d.dish_id) 
                          JOIN rating_restaurant res ON res.res_ID = r.rate_on_id
                          WHERE r.rate_by_id = %s''',[current_user.id])
        review = cursor.fetchall()


    with connection.cursor() as cursor:
        cursor.execute('''SELECT distinct username FROM auth_user WHERE id in
             (SELECT friend_id FROM user_friendship WHERE creator_id = %s)''', 
                    [current_user.id])
        friends = cursor.fetchall()

    context = {'profile': profile, 'friends':friends, 'review':review}
    return render(request, 'profile.html', context)

@login_required
def log_out(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("/")


@login_required
def edit_review(request,review_id): 
    if request.method == "POST":   
        review = Reviews.objects.get(pk=review_id)
        form = ReviewForm(request.POST, instance = review)  
        if form.is_valid():  
            form.save()  
            return redirect("/profile") 

    review = Reviews.objects.get(pk=review_id)
    return render(request,'edit_review.html', {'review':review}) 

@login_required
def recommend_friend(request):
    current_user = request.user

    with connection.cursor() as cursor:
        cursor.execute('''SELECT distinct V2.user_id
                    From rating_restaurant_visit_by V1 join rating_restaurant_visit_by V2
                    On V1.restaurant_id=V2.restaurant_id and V1.user_id
                    =%s and V2.user_id<> V1.user_id and V2.user_id not in 
                    (SELECT friend_id FROM user_friendship WHERE creator_id = %s)
                    union
                    select distinct U2.user_id
                    From user_information U1 join user_information U2
                    On U1.Favorite_Cuision = U2.Favorite_Cuision 
                    and U1.user_id<>U2.user_id and U1.user_id=%s and U1.user_id not in
                    (SELECT friend_id FROM user_friendship WHERE creator_id = %s)''', 
                    [current_user.id,current_user.id,current_user.id,current_user.id])
        user = cursor.fetchall()

    for u in user:
        print(u[0],current_user.id)
        with connection.cursor() as cursor:
            cursor.execute('''INSERT INTO user_friendship(creator_id,friend_id)
                VALUES(%s, %s)''', [current_user.id,u[0]])

    return redirect("/profile") 

user/templates/edit_review.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
<form method="POST" class="post-form" action="{% url 'user:edit_review' review.id %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Review</h3>  
    </div>  
  </div>  
 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Rating:</label>  
    <div class="col-sm-4">  
        <input type="number" name="rating" id="id_rate" value="{{ review.rating }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Comment:</label>  
    <div class="col-sm-4">  
        <input type="text" name="comment" id="id_comment" required maxlength="100" value="{{ review.comment }}" />  
    </div>  
 
  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock content %}

user/templates/information.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}

<style>
.slidecontainer {
  width: 50%;}
.slider{height:0px;}
.slider li{height: 0px;}
#widget-block{margin-top:0px;}
</style>

<style>
html{
  background:url(https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=karly-gomez-lK1Q5RyD6tc-unsplash.jpg) no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size:cover;
}
</style>

<form method="POST" class="post-form" action="{% url 'user:information' %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update User Profile</h3>  
    </div>  
  </div>  
 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">First Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="FirstName" id="id_ename" required maxlength="100" value="{{ information.FirstName }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Major:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Major" id="id_Major" required maxlength="20" value="{{ information.Major }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Gender:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Gender" id="id_Gender" required maxlength="20" value="{{ information.Gender }}" />  
    </div>  
  </div>
  
  <div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Favorite Cuision:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Favorite_Cuision" id="id_Favorite_Cuision" required maxlength="20" value="{{ information.Favorite_Cuision }}" />  
    </div>  
  </div>

  <div>
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Favorite Restaurant:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Favorite_Restaurant" id="id_Favorite_Restaurant" required maxlength="20" value="{{ information.Favorite_Restaurant }}" />  
    </div>  
  </div>

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  

<!--     <h5>Enter Your Recommendation Preference</h5> 

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="slidecontainer">
      <input type="range" min="1" max="100" value="50" class="slider" id="myRange">
      <p>Value: <span id="visit"></span></p>
    </div>

    <div class="slidecontainer">
      <input type="range" min="1" max="100" value="50" class="slider" id="myRange">
      <p>Value: <span id="duration"></span></p>
    </div>

    <div class="slidecontainer">
      <input type="range" min="1" max="100" value="50" class="slider" id="rating_out">
      <p>Value: <span id="rating"></span></p>
    </div>


    <div class="slidecontainer">
      <input type="range" min="1" max="100" value="50" class="slider" id="price_out">
      <p>Value: <span id="price"></span></p>
    </div>

    <script>
      
    var slider = document.getElementById("price_out");
    var output = document.getElementById("price");
    output.innerHTML = slider.value;
    slider.oninput = function() {
      output.innerHTML = this.value;
    }
    </script>
    
    <script>

    var slider = document.getElementById("rating_out");
    var output = document.getElementById("rating");
    output.innerHTML = slider.value;
    slider.oninput = function() {
      output.innerHTML = this.value;
    }
    </script> -->

    
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  

    </div>  
</form>  


{% endblock content %}

user/templates/login.html
{% extends "header.html" %}<!-- extend some templates -->

{% block content %}

<!--   {% if messages%}
      <script>
          {% for msg in messages %}
              alert('{{ msg.message }}');
          {% endfor %}
      </script>
  {% endif %} -->

<style>
html{
  background:url(https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=karly-gomez-lK1Q5RyD6tc-unsplash.jpg) no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size:cover;
}
</style>


  <div class="row">
    <div class="col s12 m6 l6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
		  <form method="POST">
		    {% csrf_token %}
		    {{form.as_p}}
		    <!-- p stands for paragraph -->

		    <button class="btn" style="background-color:grey; color:white" type="submit">Log In</button>

		    
		  </form>
        </div>
      </div>
    </div>
  </div>

 &nbsp;  &nbsp; if you don't have an account, <a href="/login"><strong>register</strong></a> for one.

  <!-- next we need view to point to this html page, so let's edit views.py now -->
{% endblock %}

user/templates/profile.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}


	<div class="content-section">
	  <div class="user" >

	    <div class="user-info" style="left;">
	      <h2 class="account-heading">{{profile.FirstName}}</h2>
	      <p class="text-secondary"> Major:{{profile.Major}}</p>
	      <p class="text-secondary"> Gender:{{profile.Gender}}
	      </p>
	      <p class="text-secondary"> Favorite Cuision:{{profile.Favorite_Cuision}}</p>
	      <p class="text-secondary"> Favorite Restaurant:{{profile.Favorite_Restaurant}}</p>

	    </div>

	    <div class="friend-info" style="right;">
	      <h4 class="account-heading">Friends of {{profile.FirstName}}</h2>

			<ul>
				
			    {% for f in friends %}

			        <p class="text-secondary">{{f.0}}</p>

			    {% endfor %}
			</ul>

	    </div>

	    <center><a href="{% url 'user:recommend_friend' %}" class="btn btn-primary">Recommend Friend</a></center> 

	    <div class="review">
	      <h4 class="account-heading">My Review</h2>
			<html><head>
		        <style>
		            table {
		                font-family: arial, sans-serif, font-size=1;
		                border-collapse: collapse;
		                width: 100%;
		            }
		        td, th {
		            text-align: left;
		            padding: 8px;
		            width: 21%;
		        }
		        </style>
		        </head><body>
		            
		        <table>
		            <tr>
		            	<th>Restaurant</th>
		                <th>Dish Name</th>
		                <th>Rating</th>
		                <th>Comment</th>
		                <th>Edit Your Review</th>
		            
		            {% for r in review %}
		            </tr>
		            <tr>
		                <td>{{r.0}}</td>
		                <td>{{r.1}}</td>
		                <td>{{r.2}}</td>
		                <td>{{r.3}}</td>
		                <td><a href="{% url 'user:edit_review' review_id=r.4 %}"><span style="left: 2em;" class="glyphicon glyphicon-pencil">Edit your Review</span></a> </td>
		            </tr>
		            {% endfor %}
		        </table>
		            
		        </body>
		    </html>

	    </div>

	  </div>


	  
	</div>
{% endblock content %}

user/templates/register.html
{% extends "header.html" %}<!-- extend some templates -->


{% block content %}

<style>
html{
  background:url(https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&dl=karly-gomez-lK1Q5RyD6tc-unsplash.jpg) no-repeat center center fixed;
  -webkit-background-size:cover;
  -moz-background-size:cover;
  -o-background-size:cover;
  background-size:cover;
}
</style>


  <div class="row">
    <div class="col s12 m6 l8">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
		  <form method="POST">
		    {% csrf_token %}
		    {{form.as_p}}
		    <!-- p stands for paragraph -->

		    <button class="btn" style="background-color:yellow; color:blue" type="submit">register</button>
		  </form>
        </div>
      </div>
    </div>
  </div>


   &nbsp;  &nbsp; If you already have an account, <a href="/login"><strong>login</strong></a> instead.
  <!-- next we need view to point to this html page, so let's edit views.py now -->
{% endblock %}

user/templates/review.html
{% extends "header.html" %}<!-- extend some templates -->
{% block content %}
    
<h5>Write a Review</h5>
<form action="{% url 'user:review' dish_id res_ID%}" method="POST">
{% csrf_token %}
<label>Rating(from 1 to 5): </label><br>
<input type="text" name="rating"><br>
<label>Comment: </label><br>
<input type="text" name="comment"><br>
<input type="submit" value="submit">
</form> 


{% endblock content %}